sudo: false

language: python

cache: pip

python:
  - "3.5"

notifications:
  email: false

install:
  - pip install -r requirements.txt

script:
  - python setup.py install
  - cd tests
  - nosetests

